seed: 42
num_steps: 4000
train_bs: 100
val_bs: 200
report_freq: 500
eval_freq: 2000

test_mode: False

defaults:
  - lr_sched: onecycle
  - epsilon_sched: exponential
  - momentum_sched: onecycle
  - model: fully_connected
    
loss:
  _target_: main.get_cross_entropy_loss

image_generator:
  _target_: tensorflow.keras.preprocessing.image.ImageDataGenerator
  # featurewise_center: False
  # featurewise_std_normalization: False
  # rotation_range: 0
  width_shift_range: 0.1  # frac of total width
  height_shift_range: 0.1  # frac of total height
  horizontal_flip: True
  # vertical_flip: False
  # brightness_range: (0.9, 1.1)
  # zoom_range: [0.5,1.0]
  # cval: 0.
  preprocessing_function: 
    _target_: data.get_random_eraser
    v_l: -0.5
    v_h: 0.5
    pixel_level: False
